### ISSUE TITLE
kubernetes 1.17 requires schema

### ISSUE THREAD

**Issue by ninjaslothx** [purestorage/helm-charts#161] opened 2020-01-23 23:55 UTC
I am on k8s 1.17 and am getting an error during deploy. 

The CustomResourceDefinition "psoplugins.purestorage.com" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required

From what I can understand from https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema 
If using apiextensions.k8s.io/v1 schemas are now required? 

Also I'm not very familiar with CRD's at this stage but this indentation looked off:
https://github.com/purestorage/helm-charts/blob/master/operator-k8s-plugin/install.sh#L125

Which results in an unknown field "subresources" unless the indentation is moved in to the name scope

**Comment by sdodsley** [comment] 2020-01-24 15:13
I suspect this is caused by #151. Here we tried to remove all the beta API references. We probably shouldn't have done this for the `apiextensions` API.

**Comment by trevormeiss** [comment] 2020-01-24 17:45
Thanks for opening this issue, @ninjaslothx. We are currently working on a solution.

**Comment by Pure-AdamuKaapan** [comment] 2020-01-30 19:49
@ninjaslothx we're working on a fix in #166 . Hopefully should be good to go pretty soon.

**Comment by Pure-AdamuKaapan** [comment] 2020-02-19 19:39
#166 has been merged which should fix this, closing. If you continue to experience issues please comment on this issue/re-open and we'll address it. Thanks!

**Closed by Pure-AdamuKaapan** 2020-02-19 19:39 UTC
Labels: :beetle:bug, :cloud: k8s
